### ISSUE TITLE
bpmn.io: XML validation errors

### ISSUE THREAD

**Issue by krat0s** [bpmn-miwg/bpmn-miwg-demos#11]
Tool name: bpmn.io
Tool version: 0.9.2
Test case id: 2015-06-15-19-omg-technical-meeting-berlin/hidden-attribute-interchange
Test procedure: import
Description: The XML file does not validate.
- Line: 144 Column: 8 The element 'userTask' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL' has invalid child element 'documentation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'. List of possible elements expected: 'auditing, monitoring, categoryValueRef, incoming, outgoing, ioSpecification, property, dataInputAssociation, dataOutputAssociation, resourceRole, performer, humanPerformer, potentialOwner, loopCharacteristics, multiInstanceLoopCharacteristics, standardLoopCharacteristics, rendering' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'.
- Line: 166 Column: 8 The element 'userTask' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL' has invalid child element 'documentation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'. List of possible elements expected: 'auditing, monitoring, categoryValueRef, incoming, outgoing, ioSpecification, property, dataInputAssociation, dataOutputAssociation, resourceRole, performer, humanPerformer, potentialOwner, loopCharacteristics, multiInstanceLoopCharacteristics, standardLoopCharacteristics, rendering' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'.
- Line: 250 Column: 8 The element 'userTask' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL' has invalid child element 'documentation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'. List of possible elements expected: 'auditing, monitoring, categoryValueRef, incoming, outgoing, ioSpecification, property, dataInputAssociation, dataOutputAssociation, resourceRole, performer, humanPerformer, potentialOwner, loopCharacteristics, multiInstanceLoopCharacteristics, standardLoopCharacteristics, rendering' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'.
- Line: 274 Column: 8 The element 'userTask' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL' has invalid child element 'documentation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'. List of possible elements expected: 'auditing, monitoring, categoryValueRef, incoming, outgoing, ioSpecification, property, dataInputAssociation, dataOutputAssociation, resourceRole, performer, humanPerformer, potentialOwner, loopCharacteristics, multiInstanceLoopCharacteristics, standardLoopCharacteristics, rendering' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'.
- Line: 329 Column: 8 The element 'subProcess' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL' has invalid child element 'documentation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'. List of possible elements expected: 'auditing, monitoring, categoryValueRef, incoming, outgoing, ioSpecification, property, dataInputAssociation, dataOutputAssociation, resourceRole, performer, humanPerformer, potentialOwner, loopCharacteristics, multiInstanceLoopCharacteristics, standardLoopCharacteristics, laneSet, flowElement, adHocSubProcess, boundaryEvent, businessRuleTask, callActivity, callChoreography, choreographyTask, complexGateway, dataObject, dataObjectReference, dataStoreReference, endEvent, event, eventBasedGateway, exclusiveGateway, implicitThrowEvent, inclusiveGateway, intermediateCatchEvent, intermediateThrowEvent, manualTask, parallelGateway, receiveTask, scriptTask, sendTask, sequenceFlow, serviceTask, startEvent, subChoreography, subProcess, task, transaction, userTask, artifact, association, group, textAnnotation' in namespace 'http://www.omg.org/spec/BPMN/20100524/MODEL'.
- Line: 882 Column: 23 The 'http://www.omg.org/spec/DD/20100524/DI:name' attribute is not declared.
- Line: 882 Column: 59 The 'http://www.omg.org/spec/DD/20100524/DI:resolution' attribute is not declared.
- Line: 1136 Column: 23 The 'http://www.omg.org/spec/DD/20100524/DI:name' attribute is not declared.
- Line: 1136 Column: 62 The 'http://www.omg.org/spec/DD/20100524/DI:resolution' attribute is not declared.

**Comment by falko** [comment]
I have a workaround for these issues until the tool is fixed.

**Comment by falko** [comment]
The following schema validation issues where discovered in the dry run on May 13 and have been fixed today: bpmn-io/bpmn-js#284 & bpmn-io/bpmn-js#285
