### ISSUE TITLE
element 'inputOutputSpecification' does not exists

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#15]
We find the following, line 97 (and line 182 with another id)

```
<inputOutputSpecification id="Bpmn_InputOutputSpecification_Y6GAsLH1EeSuDf0W70XLGw">
```

But the element 'inputOutputSpecification' does not exists, it should be ioSpecification, as specified line 902 of the semantic.xsd

```
<xsd:element name="ioSpecification" type="tInputOutputSpecification" />
```

**Comment by falko** [comment]
Interesting. This could be a mismatch between the BPMN CMOF and XSD. However, I have a workaround for this.

**Comment by alexismeneses** [comment]
@falko, I don't think there's a mismatch. In CMOF, the property on `Activity` and `CallableElement` classes is named `ioSpecification` (like in XSD, that's the type of this property which is named `InputOutputSpecification`)

BPMN20.cmof - line 1103

      <ownedAttribute xmi:type="cmof:Property"
                      xmi:id="Activity-ioSpecification"
                      name="ioSpecification"
                      type="InputOutputSpecification"
                      lower="0"
                      isComposite="true"
                      association="A_ioSpecification_activity"/>

BPMN20.cmof - Line 767

      <ownedAttribute xmi:type="cmof:Property"
                      xmi:id="CallableElement-ioSpecification"
                      name="ioSpecification"
                      type="InputOutputSpecification"
                      lower="0"
                      isComposite="true"
                      association="A_ioSpecification_callableElement"/>

Did you see a mismatch for any other reason?

**Comment by falko** [comment]
@alexismeneses thanks for checking this. In bpmn.io we are directly working on the meta model provided by the spec. That's why we shouldn't have the names wrong. But we'll look into this.
