### ISSUE TITLE
prefix xs is not associated with any namespace

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#16]
We can find the following, line 442

```
structureRef="xs:tString"
```

but the xs prefix is not associated with any namespace in the definitions element attributes. 
In the original file we find

```
xmlns:xs="http://xsdTypes.org/"
```

**Comment by falko** [comment]
Why is this in the model at all? Does this have a meaning for W4?

**Comment by falko** [comment]
I have a workaround for this issue in bpmn.io

**Comment by benmichel** [comment]
Yes, it is necessary to make the link between the structureRef for the itemDefinition and the imported file defining the referenced structureRef

We have 
```
xmlns:xs="http://xsdTypes.org/" 
```
and
```
<import importType="http://www.w3.org/2001/XMLSchema" 
             location="xsdTypes.xsd" 
             namespace="http://xsdTypes.org/"/>
```
and
```
<itemDefinition id="xsdString" 
                         isCollection="false" 
                         itemKind="Information" 
                         structureRef="xs:tString"/>
```

which means the 'tString' structureRef is define in the namespace associated with prefix 'xs', which is 'http://xsdTypes.org/', and the import element explicit that all structure define in file 'xsdTypes.xsd' are of the namespace 'http://xsdTypes.org/'.
So the xmlns:xs="http://xsdTypes.org/ is needed to make the link between the structureRef of the itemDef and it's definition

**Comment by falko** [comment]
Reported as bpmn-io/bpmn-js#278
