### ISSUE TITLE
itemDefinitions are missing

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#18]
The 'itemDefinition' elements are missing

```
<itemDefinition id="xsdString" isCollection="false" itemKind="Information" structureRef="xs:tString"/>
<itemDefinition id="xsdBool" isCollection="false" itemKind="Information" structureRef="xs:tBool"/>
```

**Comment by zmisiak** [comment]
Item Definitions are now exported. Waiting for MIWG members confirmation to close this issue.

**Comment by falko** [comment]
@benmichel could you check if the file works in W4 after the next dry run is complete?

**Comment by benmichel** [comment]
I will wait for the next dry run too complete to check, but according to issues #32 and 33 all issues from adonis tool seam to have been fixed

**Comment by zmisiak** [comment]
Confirmed by @benmichel and closed
