### ISSUE TITLE
DataObjects have no itemSubjectRef and there ids have been modified

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#19]
The attribute 'itemSubjectRef' is missing on data objects and the 'id' attribute of data objects have been modified

**Comment by zmisiak** [comment]
Fixed.

Signavio input:
      `<dataObject id="sid-e0468daf-8953-475d-b38a-d7f40e4d4e98" isCollection="false" itemSubjectRef="xsdBool" name="approved"/>`
      `<dataObject id="sid-a47ed49b-923d-4adb-8f69-79a9e6e3e4c1" isCollection="false" itemSubjectRef="xsdString" name="clarified"/>`

ADONIS output:
      `<dataObject name="approved" id="sid-e0468daf-8953-475d-b38a-d7f40e4d4e98"
                  isCollection="false"
                  itemSubjectRef="xsdBool"/>`
      `<dataObject name="clarified" id="sid-a47ed49b-923d-4adb-8f69-79a9e6e3e4c1"
                  isCollection="false"
                  itemSubjectRef="xsdString"/>`

Waiting for confirmation from @benmichel to close the issue

**Comment by zmisiak** [comment]
Confirmed and closed
