### ISSUE TITLE
Potential owners have been removed

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#21]
All potential Owners have been removed from user tasks

**Comment by zmisiak** [comment]
Resources and Potential owners are now preserved. Waiting for confirmation from other MIWG members, so that I can close.

**Comment by falko** [comment]
@benmichel could you check if the file works in W4 after the next dry run is complete?

**Comment by benmichel** [comment]
I will wait for the next dry run too complete to check, but according to issues #32 and 33 all issues from adonis tool seam to have been fixed
