### ISSUE TITLE
Discrepancies in pool header between Sparx and (W4 or Trisotech) 

### ISSUE THREAD

**Issue by Francois-W4** [bpmn-miwg/bpmn-miwg-demos#34]
when opening diagram created by Sparx with W4 BPMN+ Composer or Trisotech Web Modeler, the pool header is visually in conflict with the lanes header in both target products.
Looks like it is a difference of interpretation of the standard that needs to be sorted out to identify where the issue comes from (BPMN, sparx, w4, trisotech...)

W4 rendering of sparx diagram (don't mind the pink link):
![sparx-w4](https://cloud.githubusercontent.com/assets/6552230/7743689/72d593be-ff9d-11e4-933e-c3fd33f79aa6.PNG)

trisotech rendering of sparx diagram:
![sparx-trisotech](https://cloud.githubusercontent.com/assets/6552230/7743692/77923ace-ff9d-11e4-8f05-f35ac30e3d2e.PNG)

**Comment by benmichel** [comment]
A bug present in the w4 bpmn+ composer is responsable for this rendering in this composer. It will be corrected shortly

**Comment by benmichel** [comment]
This issue is now fixed for W4 Bpmn+ composer, it should be confirmed with the next dry run
