### ISSUE TITLE
wrong iospecification

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#37]
- The ioSpecification are corrupted : Id attributes were lost, the dataOutput elements changed ids, lost name and itemSubjectRef and input sets were emptied.
- new empty iospecification where added on all activity that does not already have iospecification. Empty iospecification are not executable valid

**Comment by zmisiak** [comment]
IDs in the iospecification are no longer reset. Waiting for MIWG members confirmation.

**Comment by zmisiak** [comment]
Empty iospecification blocks are no longer exported.
Waiting for @benmichel confirmation to close

**Comment by zmisiak** [comment]
Confirmed
