### ISSUE TITLE
Zero dimensions on label boxes

### ISSUE THREAD

**Issue by bzinchenko** [bpmn-miwg/bpmn-miwg-demos#41]
All label boxes have zero height and width. For instance:
```
            <bpmndi:BPMNLabel>
               <omgdc:Bounds height="0" width="0" x="985" y="88"/>
            </bpmndi:BPMNLabel>
```
As a result, label texts are not visible.

**Comment by dgagne** [comment]
Issue related to older version

**Comment by Francois-W4** [comment]
Latest commint on the git hub of the BPMN file contains non-zero label size.
