### ISSUE TITLE
Missing name in DataInput/Output 

### ISSUE THREAD

**Issue by lricco** [bpmn-miwg/bpmn-miwg-demos#48]
All the dataInputs and dataOutputs inside the tasks do not have a name. 
It is not mandatory for the BPMN Specification, but having them could help during the demo to better understand the data flow. In particular it could help when setting the targetRef/sourceRef of the dataAssociations.

Could we add them?

**Comment by SimonRinguette** [comment]
I'm correcting it for the version that will become C5
