### ISSUE TITLE
Implementation for user task

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#5]
In the demo execution file [C.1.0](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/master/2015-06-15-19-omg-technical-meeting-berlin/execution-demo/C.1.0-engine-pool-extracted-by-camunda-cycle.bpmn), the implementation attribute for each User Task is set to "webService".

As decided in issue [#414](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/issues/414) could we possibly use ##unspecified so each vendor participating in the execution demo could choose which implementation it wishes to use ?

**Comment by falko** [comment]
Yes, that's fine for Camunda BPM and probably Activiti as well.

**Comment by falko** [comment]
implementation="##unspecified" is set in the model
