### ISSUE TITLE
Process not linked to Collaboration

### ISSUE THREAD

**Issue by ChrisSchoe** [bpmn-miwg/bpmn-miwg-demos#52]
Hi everyone, 

while trying to work out some kinks occurring during the MIWG meeting round trips I came upon a problem with the collaboration/participants in the vacation request bpmn, cf. [here](
https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/1ebb8272d4aac0978a6bb33b5693ab6e76d6968f/2021-12-06-omg-technical-meeting-longbeach/Vacation%20Request.bpmn). I have already discussed it with @falko and we concluded roughly the following:

The file contains a collaboration and that collaboration is the element that is given to the di:BPMNPlane as its bpmn element to represent in the BPMNdiagram part of the XML. Thus, the displayed diagram should be a collaboration.

 Apart from the collaboration, the file also contains a process. However, this process has no corresponding participant in collaboration linked to it via _processRef_. Moreover, its _id_ is also not linked as a BPMNElement in the diagram section of the XML. 
**Thus, as it is now, the diagram represents a collaboration that has no connection to the process contained in the same file.** 

What most vendors' tools in the MIWG meetings displayed were process elements outside of any pool, connected to a blackbox pool via several message flows. Evidently, these are representations of correct bpmn diagrams, as even the specification itself contains such visualisations. However, my understanding of the specification is, that the process elements/ the process outside of any pool should still be part of a participant of the overall collaboration. 
More precisely, the specs state:

> A Collaboration can contain two (2) or more Pools (i.e., Participants). However, a Process that represents the work
performed from the point of view of the modeler or the modeler’s organization can be considered “internal” and is NOT
REQUIRED to be surrounded by the boundary of the Pool, while the other Pools in the Diagram MUST have their
boundary (see Figure 9.5).
_[Business Process Model and Notation (BPMN) Version 2.0, p.113]_

Therefore, I'd argue that all processes that are to be represented in a collaboration need to be referenced in one of their participants.

**Comment by falko** [comment]
During the meetings of 2021-06-09 and 2021-07-14 it has been agreed that the second participant should be in the semantic model of the collaboration even if not visually shown. In order to give vendors enough time to adjust their tools, we removed this part from the 2021 demo. It should be added to a future test case though.

**Comment by MaxTru** [comment]
@falko just to be sure: so this means the existing [`Vacation Request`](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/master/2021-12-06-omg-technical-meeting-longbeach/Vacation%20Request.png) bpmn will be removed from the [2021 demo](https://github.com/bpmn-miwg/bpmn-miwg-demos/tree/master/2021-12-06-omg-technical-meeting-longbeach)? So far it is still in there.

**Comment by falko** [comment]
@MaxTru yes, the second participant will not be part of the demo. Thx for pointing out that the file in this repo has not been updated with the latest version from Dropbox. I'm reopening the issue and we can fix it through #51
