### ISSUE TITLE
Set Collaboration 'isClosed' parameter to "true"

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#6]
In the demo execution file [C.1.0](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/master/2015-06-15-19-omg-technical-meeting-berlin/execution-demo/C.1.0-engine-pool-extracted-by-camunda-cycle.bpmn), the collaboration 'isClosed' attribute is set to "false". It would simplify things for W4 to set this attribute to "true" (due to a technical choices we made during the development of our engine). Would it be ok to do so ?

**Comment by falko** [comment]
Yes, that's fine.

**Comment by falko** [comment]
isClosed="true" is set in the model
