### ISSUE TITLE
No incoming nor outgoings from gateways

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#7]
In file [C.1.0-engine-pool-extracted-by-camunda-cycle.bpmn](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/master/2015-06-15-19-omg-technical-meeting-berlin/execution-demo/C.1.0-engine-pool-extracted-by-camunda-cycle.bpmn), Gateways "invoice_approved" and "reviewSuccessful_gw" does not have any incoming nor outgoings 

    <exclusiveGateway id="invoice_approved" name="Invoice&#xA;approved?" gatewayDirection="Diverging">
       <extensionElements>
          <signavio:signavioMetaData metaKey="bgcolor" metaValue="#ffffff"/>
          <signavio:signavioMetaData metaKey="adaptertype" metaValue=""/>
          <signavio:signavioMetaData metaKey="userstory" metaValue="[]"/>
          <signavio:signavioMetaData metaKey="adapterconfiguration" metaValue=""/>
          <signavio:signavioMetaData metaKey="adapterclassname" metaValue=""/>
       </extensionElements>
    </exclusiveGateway>

    <exclusiveGateway id="reviewSuccessful_gw" name="Review&#xA;successful?" gatewayDirection="Diverging">
       <extensionElements>
          <signavio:signavioMetaData metaKey="bgcolor" metaValue="#ffffff"/>
          <signavio:signavioMetaData metaKey="adaptertype" metaValue=""/>
          <signavio:signavioMetaData metaKey="userstory" metaValue="[]"/>
          <signavio:signavioMetaData metaKey="adapterconfiguration" metaValue=""/>
          <signavio:signavioMetaData metaKey="adapterclassname" metaValue=""/>
       </extensionElements>
    </exclusiveGateway>

**Comment by benmichel** [comment]
Same for User Task "reviewInvoice", Start Event "StartEvent_1" and Service Task "archiveInvoice"

**Comment by falko** [comment]
Feel free to add them if you need them.

**Comment by falko** [comment]
It looks like they have been added.
