### ISSUE TITLE
[hidden-attribute-interchange / Fridge repair service] - wrong labelStyle references

### ISSUE THREAD

**Issue by alexismeneses** [bpmn-miwg/bpmn-miwg-demos#9]
The following issue applies to the file `2015-06-15-19-omg-technical-meeting-berlin/hidden-attribute-interchange/Fridge repair service.bpmn`

In the **BPMNDiagram** named _Fridge Repair Process (1)_, `labelStyle` attributes of **BPMNLabel**s refer to **BPMNLabelStyle**s that are not present in the same **BPMNDiagram**. Instead, they are present in the other **BPMNDiagram** named _Perform emergency repair (1)_

Example

    <bpmndi:BPMNLabel labelStyle="_964cbbf6-0e1c-44dc-a6a8-65f3498035f8" ...>

is present in 

    <bpmndi:BPMNDiagram name="Fridge Repair Process (1)" > ... </bpmndi:BPMNDiagram> 

but

    <bpmndi:BPMNLabelStyle id="_964cbbf6-0e1c-44dc-a6a8-65f3498035f8">

is a child of 

    <bpmndi:BPMNDiagram name="Perform emergency repair (1)" > ... </bpmndi:BPMNDiagram>

**Comment by krat0s** [comment]
Thank you for pointing that out. The labelStyle references should now be fixed. A new diagram has been committed.

**Comment by benmichel** [comment]
This bug can also be found in trisotech bpmn modeler submission for this demo

**Comment by SimonRinguette** [comment]
We have also fixed it in the Trisotech tool.
